[package]
name = "dominion_macros"
version = "0.1.0"
authors = ["Chenkail <40770208+Chenkail@users.noreply.github.com>"]
edition = "2018"
license = "AGPLv3"

[dependencies]

[dev-dependencies]
dominion = { path = "../" }
serde = { version = "1.0", features = ["derive"] }
typetag = "0.1"
